name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
    contents: write

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check cmake
      run: cmake --version
      
    - name: set PATH, check mingw version, cmake generate, build and install
      shell: cmd
      run: |
        set CD_LINUX=%CD:\=/%
        cmake.exe -G"Visual Studio 17 2022" ^
        -DCMAKE_BUILD_TYPE=Release ^
        -DBUILD_SHARED_LIBS=OFF ^
        -B./cmake-build &&^
        cd cmake-build && cmake --build . --config Release --target ALL_BUILD -v -- /maxcpucount
        
    - shell: cmd
      run: |
        cd cmake-build &&^
        dir /S
      
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: "cmake-build/Release"
        filename: "${{ github.event.repository.name }}-${{ github.ref_name }}-msvc2022.zip"
      
    - name: Release prebuilt
      uses: ncipollo/release-action@v1
      with:
        artifacts: "cmake-build/Release/${{ github.event.repository.name }}-${{ github.ref_name }}-msvc2022.zip"
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
